CREATE OR REPLACE task upsert_articles_table
warehouse = COMPUTE_WH
SCHEDULE = 'USING CRON 00 19 * * * Asia/Tokyo'
as
MERGE INTO HANDM.public.articles AS target
  USING HANDM.public.TEMP_ARTICLES AS source
  ON (target.article_id = source.article_id )
  WHEN MATCHED THEN
  UPDATE SET
    target.PROD_NAME = source.PROD_NAME,
    target.product_CODE = source.product_CODE,
    target.ARTICLE_ID = source.ARTICLE_ID,
    target.PRODUCT_TYPE_NO = source.PRODUCT_TYPE_NO,
    target.PRODUCT_TYPE_NAME= source.PRODUCT_TYPE_NAME,
    target.PRODUCT_GROUP_NAME = source.PRODUCT_GROUP_NAME,
    target.GRAPHICAL_APPEARANCE_NO = source.GRAPHICAL_APPEARANCE_NO,
    target.GRAPHICAL_APPEARANCE_NAME = source.GRAPHICAL_APPEARANCE_NAME,
    target.COLOUR_GROUP_CODE = source.COLOUR_GROUP_CODE,
    target.COLOUR_GROUP_NAME = source.COLOUR_GROUP_NAME,
    target.PERCEIVED_COLOUR_VALUE_ID = source.PERCEIVED_COLOUR_VALUE_ID,
    target.PERCEIVED_COLOUR_VALUE_NAME = source.PERCEIVED_COLOUR_VALUE_NAME,
    target.PERCEIVED_COLOUR_MASTER_ID = source.PERCEIVED_COLOUR_MASTER_ID,
    target.PERCEIVED_COLOUR_MASTER_NAME = source.PERCEIVED_COLOUR_MASTER_NAME,
    target.DEPARTMENT_NO = source.DEPARTMENT_NO,
    target.DEPARTMENT_NAME = source.DEPARTMENT_NAME,
    target.INDEX_CODE = source.INDEX_CODE,
    target.INDEX_NAME = source.INDEX_NAME,
    target.INDEX_GROUP_NO = source.INDEX_GROUP_NO,
    target.INDEX_GROUP_NAME = source.INDEX_GROUP_NAME,
    target.SECTION_NO = source.SECTION_NO,
    target.SECTION_NAME = source.SECTION_NAME,
    target.GARMENT_GROUP_NO = source.GARMENT_GROUP_NO,
    target.GARMENT_GROUP_NAME = source.GARMENT_GROUP_NAME,
    target.DETAIL_DESC = source.DETAIL_DESC
  WHEN NOT MATCHED THEN
  INSERT(
  ARTICLE_ID,
  PRODUCT_CODE,
  PROD_NAME,
  PRODUCT_TYPE_NO,
  PRODUCT_TYPE_NAME,
  PRODUCT_GROUP_NAME,
  GRAPHICAL_APPEARANCE_NO,
  GRAPHICAL_APPEARANCE_NAME,
  COLOUR_GROUP_CODE,
  COLOUR_GROUP_NAME,
  PERCEIVED_COLOUR_VALUE_ID,
  PERCEIVED_COLOUR_VALUE_NAME,
  PERCEIVED_COLOUR_MASTER_ID,
  PERCEIVED_COLOUR_MASTER_NAME,
  DEPARTMENT_NO,
  DEPARTMENT_NAME,
  INDEX_CODE,
  INDEX_NAME,
  INDEX_GROUP_NO,
  INDEX_GROUP_NAME,
  SECTION_NO,
  SECTION_NAME,
  GARMENT_GROUP_NO,
  GARMENT_GROUP_NAME,
  DETAIL_DESC)
VALUES(
  source.ARTICLE_ID,
  source.PRODUCT_CODE,
  source.PROD_NAME,
  source.PRODUCT_TYPE_NO,
  source.PRODUCT_TYPE_NAME,
  source.PRODUCT_GROUP_NAME,
  source.GRAPHICAL_APPEARANCE_NO,
  source.GRAPHICAL_APPEARANCE_NAME,
  source.COLOUR_GROUP_CODE,
  source.COLOUR_GROUP_NAME,
  source.PERCEIVED_COLOUR_VALUE_ID,
  source.PERCEIVED_COLOUR_VALUE_NAME,
  source.PERCEIVED_COLOUR_MASTER_ID,
  source.PERCEIVED_COLOUR_MASTER_NAME,
  source.DEPARTMENT_NO,
  source.DEPARTMENT_NAME,
  source.INDEX_CODE,
  source.INDEX_NAME,
  source.INDEX_GROUP_NO,
  source.INDEX_GROUP_NAME,
  source.SECTION_NO,
  source.SECTION_NAME,
  source.GARMENT_GROUP_NO,
  source.GARMENT_GROUP_NAME,
  source.DETAIL_DESC
  );

-- SELECT * FROM CUSTOMER;
-- SELECT * FROM HANDM.public.TEMP_CUSTOMER_TABLE;

--upsert_customer_table
CREATE OR REPLACE task upsert_customer_table
warehouse = COMPUTE_WH
SCHEDULE = 'USING CRON 00 19 * * * Asia/Tokyo'
as
MERGE INTO HANDM.public.customer AS target
USING HANDM.public.TEMP_CUSTOMER_TABLE AS source
ON (target.customer_id = source.customer_id)
WHEN MATCHED THEN
  UPDATE SET
    target.customer_id = source.customer_id,
    target.FN = source.FN,
    target.ACTIVE = source.ACTIVE,
    target.FASHION_NEWS_FREQUENCY = source.FASHION_NEWS_FREQUENCY,
    target.CLUB_MEMBER_STATUS = source.CLUB_MEBMER_STATUS,
    target.POSTAL_CODE = source.POSTAL_CODE
WHEN NOT MATCHED THEN
  INSERT (
    CUSTOMER_ID,
    FN,
    ACTIVE,
    CLUB_MEMBER_STATUS,
    FASHION_NEWS_FREQUENCY,
    AGE,
    POSTAL_CODE
  )
  VALUES (
    source.CUSTOMER_ID,
    source.FN,
    source.ACTIVE,
    source.CLUB_MEBMER_STATUS,
    source.FASHION_NEWS_FREQUENCY,
    source.AGE,
    source.POSTAL_CODE
  );