-- インテグレーションの作成
CREATE OR REPLACE NOTIFICATION INTEGRATION streaming_transaction_integration
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = TRUE
  GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/fivetran-handson-389804/subscriptions/streaming_transaction';

-- インテグレーションの詳細の確認
DESC INTEGRATION streaming_transaction_integration;

-- パイプの作成
CREATE OR REPLACE PIPE transaction_pipe
  AUTO_INGEST = TRUE
  INTEGRATION = streaming_transaction_integration
AS
  COPY INTO HANDM.PUBLIC.TRANSACTION (T_DAT, CUSTOMER_ID, ARTICLE_ID,PRICE,SALES_CHANNEL_ID)
  FROM (
    SELECT
      $1:t_dat::STRING AS T_DAT,
      $1:customer_id::STRING AS CUSTOMER_ID,
      $1:article_id::int AS article_id,
      $1:price::float AS PRICE ,
      $1:sales_channel_id::int AS SALES_CHANNEL_ID
      
    FROM @STOREAMING_TRANSACTION
  )
  FILE_FORMAT = (TYPE = 'JSON');


--temp_customer_tableへのsnow_pipeの構築

-- インテグレーションの作成
CREATE OR REPLACE NOTIFICATION INTEGRATION streaming_customer_integration
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = TRUE
  GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/fivetran-handson-389804/topics/streaming_customer_data';


-- パイプの作成
CREATE OR REPLACE PIPE customer_pipe
  AUTO_INGEST = TRUE
  INTEGRATION = streaming_customer_integration
AS
  COPY INTO HANDM.PUBLIC.TEMP_CUSTOMER_TABLE (CUSTOMER_ID, FN,ACTIVE,CLUB_MEBMER_STATUS,FASHION_NEWS_FREQUENCY,AGE,POSTAL_CODE)
  FROM (
    SELECT
      $1:CUSTOMER_ID::STRING AS CUSTOMER_ID,
      $1:FN::int AS FN,
      $1:ACTIVE::int AS ACTIVE,
      $1:CLUB_MEMBER_STATUS::string AS CLUB_MEMBER_STATUS ,
      $1:FASHION_NEWS_FREQUENCY::string AS FASHION_NEWS_FREQUENCY,
      $1:AGE::int AS AGE,
      $1:POSTAL_CODE::string AS POSTAL_CODE  
    FROM @STREAMING_CUSTOMER
  )
  FILE_FORMAT = (TYPE = 'JSON');

  SELECT * FROM HANDM.PUBLIC.TEMP_CUSTOMER_TABLE;



--temp_article_tableへのsnow_pipeの構築

-- インテグレーションの作成
CREATE OR REPLACE NOTIFICATION INTEGRATION streaming_articles_integration
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = TRUE
  GCP_PUBSUB_SUBSCRIPTION_NAME ='projects/fivetran-handson-389804/subscriptions/streaming_articles';

-- インテグレーションの詳細の確認
DESC INTEGRATION streaming_articles_integration;


-- パイプの作成
CREATE OR REPLACE PIPE articles_pipe
  AUTO_INGEST = TRUE
  INTEGRATION = streaming_articles_integration
AS
  COPY INTO HANDM.PUBLIC.TEMP_ARTICLES (

ARTICLE_ID,
PRODUCT_CODE,
PROD_NAME,
PRODUCT_TYPE_NO,
PRODUCT_TYPE_NAME,
PRODUCT_GROUP_NAME,
GRAPHICAL_APPEARANCE_NO,
GRAPHICAL_APPEARANCE_NAME,
COLOUR_GROUP_CODE,
COLOUR_GROUP_NAME,
PERCEIVED_COLOUR_VALUE_ID,
PERCEIVED_COLOUR_VALUE_NAME,
PERCEIVED_COLOUR_MASTER_ID,
PERCEIVED_COLOUR_MASTER_NAME,
DEPARTMENT_NO,
DEPARTMENT_NAME,
INDEX_CODE,
INDEX_NAME,
INDEX_GROUP_NO,
INDEX_GROUP_NAME,
SECTION_NO,
SECTION_NAME,
GARMENT_GROUP_NO,
GARMENT_GROUP_NAME,
DETAIL_DESC
  )
  FROM (
    SELECT
      $1:ARTICLE_ID::NUMBER(38,0) AS ARTICLE_ID,
      $1:PRODUCT_CODE::NUMBER(38,0) AS PRODUCT_CODE,
      $1:PROD_NAME::VARCHAR(16777216) AS PROD_NAM,
      $1:PRODUCT_TYPE_NO::NUMBER(38,0) AS PRODUCT_TYPE_NO,
      $1:PRODUCT_TYPE_NAME::VARCHAR(16777216) AS PRODUCT_TYPE_NAME,
      $1:PRODUCT_GROUP_NAME::VARCHAR(16777216) AS PRODUCT_GROUP_NAME,
      $1:GRAPHICAL_APPEARANCE_NO::VARCHAR(16777216) AS GRAPHICAL_APPEARANCE_NO,
      $1:GRAPHICAL_APPEARANCE_NAME::VARCHAR(16777216) AS GRAPHICAL_APPEARANCE_NAME,
      $1:COLOUR_GROUP_CODE::NUMBER(38,0) AS COLOUR_GROUP_CODE,
      $1:COLOUR_GROUP_NAME::VARCHAR(16777216) AS COLOUR_GROUP_NAME,
      $1:PERCEIVED_COLOUR_VALUE_ID::NUMBER(38,0) AS PERCEIVED_COLOUR_VALUE_ID,
      $1:PERCEIVED_COLOUR_VALUE_NAME::VARCHAR(16777216) AS PERCEIVED_COLOUR_VALUE_NAME,
      $1:PERCEIVED_COLOUR_MASTER_ID::NUMBER(38,0),
      $1:PERCEIVED_COLOUR_MASTER_NAME::VARCHAR(16777216) AS PERCEIVED_COLOUR_MASTER_NAME,
      $1:DEPARTMENT_NO::NUMBER(38,0) AS DEPARTMENT_NO,
      $1:DEPARTMENT_NAME::VARCHAR(16777216) AS DEPARTMENT_NAME,
      $1:INDEX_CODE::VARCHAR(16777216) AS INDEX_CODE,
      $1:INDEX_NAME::VARCHAR(16777216) AS INDEX_NAME,
      $1:INDEX_GROUP_NO::NUMBER(38,0) AS INDEX_GROUP_NO,
      $1:INDEX_GROUP_NAME::VARCHAR(16777216) AS INDEX_GROUP_NAME,
      $1:SECTION_NO::NUMBER(38,0) AS SECTION_NO,
      $1:SECTION_NAME::VARCHAR(16777216) AS SECTION_NAME,
      $1:GARMENT_GROUP_NO::NUMBER(38,0) AS GARMENT_GROUP_NO,
      $1:GARMENT_GROUP_NAME::VARCHAR(16777216) AS GARMENT_GROUP_NAME,
      $1:DETAIL_DESC::VARCHAR(16777216) AS DETAIL_DESC
    FROM @STOREAMING_ARTICLES
  )
  FILE_FORMAT = (TYPE = 'JSON');

  SELECT * FROM HANDM.PUBLIC.TEMP_CUSTOMER_TABLE;